[project]
name = "ems-protocol"
version = "0.1.0"
description = "AI-powered review of EMS protocols"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argparse>=1.4.0",
    "claude-agent-sdk>=0.2.87",
    "deepeval>=4.0.3",
    "dotenv>=0.9.9",
    "google-genai>=2.6.0",
    "openai>=2.38.0",
    "pycryptodome>=3.23.0",
    "pypdf>=6.12.1",
    "pyyaml>=6.0.3",
    "xai-sdk>=1.12.2",
]

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.14",
    "pytest>=9.0.3"
]

[tool.uv.sources]
my-lib = { path = "../src/ems_protocol" }
